### ISSUE TITLE
全新的React版本的弹幕姬！

### ISSUE THREAD

**Issue by LoveLoliii** [kokolokksk/catcat-dm-react#1]
使用全新UI！
Say something!

**Comment by LoveLoliii** [comment]
6.3-6.5期间 b站wss未返回弹幕消息，6.6恢复

**Comment by MistEO** [comment]
年经了属于是

**Comment by LoveLoliii** [comment]
> 年经了属于是

可以首页快速导航过来！

**Comment by LoveLoliii** [comment]
<html>
<body>


https://i0.hdslb.com/bfs/live/bbc1a0fa4924a644c861cc39e30e38d84fe219d0.webp
--



</body>
</html>

**Comment by LoveLoliii** [comment]
> ## https://i0.hdslb.com/bfs/live/bbc1a0fa4924a644c861cc39e30e38d84fe219d0.webp

金币

**Comment by MistEO** [comment]
这啥

**Comment by LoveLoliii** [comment]
记下金币的gif

**Comment by LoveLoliii** [comment]
禁言
https://api.live.bilibili.com/xlive/web-ucenter/v1/banned/AddSilentUser POST 
room_id: 房间号
tuid: target uid
msg: 123
mobile_app: web
csrf_token: xxx
csrf: xxx(与上相同)
visit_id:

**Comment by LoveLoliii** [comment]
拉黑
https://api.live.bilibili.com/xlive/app-ucenter/v2/xbanned/banned/AddBlack POST
tuid: target uid
anchor_id: 房间号
spmid: 444.8.0.0
csrf_token: xxx
csrf: xxx
visit_id:

**Comment by LoveLoliii** [comment]
屏蔽
https://api.live.bilibili.com/liveact/shield_user POST
roomid: 房间号
uid:  uid
type: 1
csrf_token: xxx
csrf: xxx
visit_id:

**Comment by LoveLoliii** [comment]
礼物列表
https://api.live.bilibili.com/xlive/web-room/v1/giftPanel/giftConfig?platform=pc&room_id=19864&area_parent_id=2&area_id=102 GET
