### ISSUE TITLE
深色主题下，弹幕输入框文字看不清

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#10]
![image](https://user-images.githubusercontent.com/18511905/224488919-11e7eb4e-6225-443b-aad1-4db83a6fa66e.png)

**Comment by LoveLoliii** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/224488919-11e7eb4e-6225-443b-aad1-4db83a6fa66e.png)

ADD TODO

**Comment by LoveLoliii** [comment]
fixed
