### ISSUE TITLE
窗口置顶偶现失效

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#11]
就一开始是能置顶的，和别的窗口来回点两下就不置顶了，甚至一直位于最底层，没法点上来（

不知道能提供什么日志？

**Comment by MistEO** [comment]
补充一下，失效的情况是：弹幕姬窗口不但不置顶，甚至一直在最底层（即其他所有窗口都在它上面），点击弹幕窗口也没有效果，始终是在最底层

**Comment by LoveLoliii** [comment]
> 补充一下，失效的情况是：弹幕姬窗口不但不置顶，甚至一直在最底层（即其他所有窗口都在它上面），点击弹幕窗口也没有效果，始终是在最底层

尚未复现

**Comment by LoveLoliii** [comment]
fixed
