### ISSUE TITLE
[Bugs]Linux下运行时任务栏图标显示不正常

### ISSUE THREAD

**Issue by zxp19821005** [kokolokksk/catcat-dm-react#13]
如题。
我已经将软件移植到了ArchLinux的AUR，详见： https://aur.archlinux.org/packages/catcat-dm-react
今天在运行时发现，在当前最新的1.9.5版本中，任务栏图标显示为Electron的图标，而不是紫色猫图标。
查看了一下目录结构，[icons](https://github.com/kokolokksk/catcat-dm-react/tree/v1.9.5/assets/icons)里面的图标和[icon.svg](https://github.com/kokolokksk/catcat-dm-react/blob/v1.9.5/assets/icon.svg)都是如此。
因此我在编译的脚本中，使用[icon.min.svg](https://github.com/kokolokksk/catcat-dm-react/blob/v1.9.5/assets/icon.min.svg) 替换了 [icon.svg](https://github.com/kokolokksk/catcat-dm-react/blob/v1.9.5/assets/icon.svg)，目前显示正常。
建议对目录结构中的文件和代码修改一下。

**Comment by LoveLoliii** [comment]
好的，感谢移植~

**Comment by LoveLoliii** [comment]
文件已替换。

**Comment by zxp19821005** [comment]
谢谢！
