### ISSUE TITLE
弹幕接收不到或者用户名*号

### ISSUE THREAD

**Issue by LoveLoliii** [kokolokksk/catcat-dm-react#14]
## 接口变动

正在查找可能原因并寻求解决方法。

**Comment by LoveLoliii** [comment]
LIVE_INTERACTIVE_GAME 此类型亦可能有弹幕
```
{
  cmd: 'LIVE_INTERACTIVE_GAME',
  data: {
    type: 2,
    uid: 12345,
    uname: 'xxx',
    uface: '',
    gift_id: 0,
    gift_name: '',
    gift_num: 0,
    price: 0,
    paid: false,
    msg: '没想到主播也能是观众',
    fans_medal_level: 19,
    guard_level: 0,
    timestamp: 1702372296,
    anchor_lottery: null,
    pk_info: null,
    anchor_info: null,
    combo_info: null
  }
}
```

**Comment by LoveLoliii** [comment]
也许是在ws加上了cookies后 弹幕数量明显变多 虽然还是*号用户，删去cookies后还是变多了

**Comment by MistEO** [comment]
![image](https://github.com/kokolokksk/catcat-dm-react/assets/18511905/a9a95ad1-3359-4702-94aa-770f7e3bef07)

现在还是*号，所以是同一个问题吗（

版本号是 v1.9.6

**Comment by LoveLoliii** [comment]
> ![image](https://private-user-images.githubusercontent.com/18511905/311489971-a9a95ad1-3359-4702-94aa-770f7e3bef07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTY4MTAsIm5iZiI6MTcxMDI5NjUxMCwicGF0aCI6Ii8xODUxMTkwNS8zMTE0ODk5NzEtYTlhOTVhZDEtMzM1OS00NzAyLTk0YWEtNzcwZjdlM2JlZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZmNjN2MzMGQ4ODVkMzdmMDZlMmVmYzYyNjBhMTk4YTVlYWMzM2I0YzhjZjY1NTAyN2FmNDJhYzhmYmFlNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eGXboeYgxkqOs51q8yayw2ujejJR2hH0yhnpFoxk8Vc)
> 
> 现在还是*号，所以是同一个问题吗（
> 
> 版本号是 v1.9.6

是的没错

**Comment by LoveLoliii** [comment]
> ![image](https://private-user-images.githubusercontent.com/18511905/311489971-a9a95ad1-3359-4702-94aa-770f7e3bef07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzE2NzUsIm5iZiI6MTcxMDQ3MTM3NSwicGF0aCI6Ii8xODUxMTkwNS8zMTE0ODk5NzEtYTlhOTVhZDEtMzM1OS00NzAyLTk0YWEtNzcwZjdlM2JlZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAyNTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOWNiNjU2NDViMjY2MTkyZWMyOTQwZDIxMTkyZWIzMDJmNjUzYTYwODhkMzJkMGEzZDNjMDI0ZDMxMDZkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WWVQ4V_LoorvN2JlnWDpUGOSqoEIu7Y3oZpdtAmFLG4)
> 
> 现在还是*号，所以是同一个问题吗（
> 
> 版本号是 v1.9.6

已修复@[v1.9.7](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.9.7)
