### ISSUE TITLE
最新发行版，plugins.json错误

### ISSUE THREAD

**Issue by owwkmidream** [kokolokksk/catcat-dm-react#16]
Error:ENOENT:nosuchfileordirectory,open'C:\Users\user\AppData\Roaming\catcat-dm-react\plugins.json'

**Comment by MistEO** [comment]
![image](https://github.com/kokolokksk/catcat-dm-react/assets/18511905/1061b9be-badd-4339-aa71-c94e9de6f6de)

遇到了同样的问题

**Comment by LoveLoliii** [comment]
[已修复](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.9.8)
