### ISSUE TITLE
请求半透明和点击穿透功能

### ISSUE THREAD

**Issue by owwkmidream** [kokolokksk/catcat-dm-react#17]
请求半透明和点击穿透功能

**Comment by LoveLoliii** [comment]
> 请求半透明和点击穿透功能

ADD TODO

**Comment by LoveLoliii** [comment]
![image](https://github.com/kokolokksk/catcat-dm-react/assets/12725100/c049675d-5a85-4dc3-a902-baefd9b571de)
先对miku主题做个半透明化的实现，后面我看下怎么写个统一调整的。

**Comment by owwkmidream** [comment]
> ![image](https://private-user-images.githubusercontent.com/12725100/313458428-c049675d-5a85-4dc3-a902-baefd9b571de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzU3NDMsIm5iZiI6MTcxMDY3NTQ0MywicGF0aCI6Ii8xMjcyNTEwMC8zMTM0NTg0MjgtYzA0OTY3NWQtNWE4NS00ZGMzLWE5MDItYmFlZmQ5YjU3MWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDExMzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OWIxZGQxMzc4NzA5NzZlNWQ4ZGE4NTAxZTU0NTUzOTE4OWVkYTIxZjRmYzNhYWIwNDdjZDE2MmE5YTFmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILQ0hTR24sZTU_GPX4uZeFciZ47CYSxrvSy2fGJX8hQ) 先对miku主题做个半透明化的实现，后面我看下怎么写个统一调整的。

那个穿透能不能做成再次点击锁图标解锁呢，如果想调整大小、发弹幕，现在都很不方便。

**Comment by LoveLoliii** [comment]
> > ![image](https://private-user-images.githubusercontent.com/12725100/313458428-c049675d-5a85-4dc3-a902-baefd9b571de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzU3NDMsIm5iZiI6MTcxMDY3NTQ0MywicGF0aCI6Ii8xMjcyNTEwMC8zMTM0NTg0MjgtYzA0OTY3NWQtNWE4NS00ZGMzLWE5MDItYmFlZmQ5YjU3MWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDExMzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OWIxZGQxMzc4NzA5NzZlNWQ4ZGE4NTAxZTU0NTUzOTE4OWVkYTIxZjRmYzNhYWIwNDdjZDE2MmE5YTFmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILQ0hTR24sZTU_GPX4uZeFciZ47CYSxrvSy2fGJX8hQ) 先对miku主题做个半透明化的实现，后面我看下怎么写个统一调整的。
> 
> 那个穿透能不能做成再次点击锁图标解锁呢，如果想调整大小、发弹幕，现在都很不方便。

这个后续看下

**Comment by LoveLoliii** [comment]
> > ![image](https://private-user-images.githubusercontent.com/12725100/313458428-c049675d-5a85-4dc3-a902-baefd9b571de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzU3NDMsIm5iZiI6MTcxMDY3NTQ0MywicGF0aCI6Ii8xMjcyNTEwMC8zMTM0NTg0MjgtYzA0OTY3NWQtNWE4NS00ZGMzLWE5MDItYmFlZmQ5YjU3MWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDExMzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OWIxZGQxMzc4NzA5NzZlNWQ4ZGE4NTAxZTU0NTUzOTE4OWVkYTIxZjRmYzNhYWIwNDdjZDE2MmE5YTFmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILQ0hTR24sZTU_GPX4uZeFciZ47CYSxrvSy2fGJX8hQ) 先对miku主题做个半透明化的实现，后面我看下怎么写个统一调整的。
> 
> 那个穿透能不能做成再次点击锁图标解锁呢，如果想调整大小、发弹幕，现在都很不方便。

穿透这个，现在可以再次点击锁图标解锁@[v1.9.9](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.9.9)

**Comment by LoveLoliii** [comment]
现在可以对不同主题的弹幕窗口进行[透明度调整](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v2.0.0)了。

**Comment by LoveLoliii** [comment]
未设置 opacity 值会导致对应组件无法显示，下一版本修复，
可临时在 ```%appdata%/catcat-dm-react/```目录下修改config.json添加默认透明度，例如```"opacity": 0.5```

**Comment by LoveLoliii** [comment]
fixed
