### ISSUE TITLE
窗口置顶不生效

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#2]
RT

已选择置顶，还是会被其他窗口挡住，关闭重开无效

另外波浪似乎也没生效

**Comment by LoveLoliii** [comment]
> RT
> 
> 已选择置顶，还是会被其他窗口挡住，关闭重开无效
> 
> 另外波浪似乎也没生效

波浪没实装

**Comment by LoveLoliii** [comment]
> RT
> 
> 已选择置顶，还是会被其他窗口挡住，关闭重开无效
> 
> 另外波浪似乎也没生效

置顶已修复。[here](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.5.0)

**Comment by MistEO** [comment]
not working

**Comment by MistEO** [comment]
> > RT
> > 已选择置顶，还是会被其他窗口挡住，关闭重开无效
> > 另外波浪似乎也没生效
> 
> 置顶已修复。[here](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.5.0)

not working ;(

**Comment by LoveLoliii** [comment]
> > > RT
> > > 已选择置顶，还是会被其他窗口挡住，关闭重开无效
> > > 另外波浪似乎也没生效
> > 
> > 
> > 置顶已修复。[here](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.5.0)
> 
> not working ;(

对的 打开弹幕窗口设置的时候载入config文件的配置会不生效 已修复下个版本发布

**Comment by LoveLoliii** [comment]
> > > RT
> > > 已选择置顶，还是会被其他窗口挡住，关闭重开无效
> > > 另外波浪似乎也没生效
> > 
> > 
> > 置顶已修复。[here](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.5.0)
> 
> not working ;(

fixed (╯°□°）╯︵ ┻━┻ [here](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.5.0)
