### ISSUE TITLE
头像显示 NaN

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#3]
![image](https://user-images.githubusercontent.com/18511905/173239558-2ea4cfee-ef35-490c-b1b6-9df7a11a06fe.png)

不知道是啥（）

**Comment by MistEO** [comment]
补一句，是最新的 v1.5.1

**Comment by MistEO** [comment]
应该是送礼物就会这样，然后 v1.5.0 看起来没有这个问题

**Comment by LoveLoliii** [comment]
> 应该是送礼物就会这样，然后 v1.5.0 看起来没有这个问题

这个版本更新了好几次 最新的应该没问题,[here](https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.5.1)

**Comment by LoveLoliii** [comment]
> 应该是送礼物就会这样，然后 v1.5.0 看起来没有这个问题

fixed！
