### ISSUE TITLE
v1.5.3 窗口置顶功能失效

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#4]
看看你还要啥信息_(:з」∠)_

![image](https://user-images.githubusercontent.com/18511905/174324333-a4396bd4-0f46-4db9-9cf3-b9839035d9d7.png)

**Comment by LoveLoliii** [comment]
嗯嗯 是初始化的时候载入设置没更新 可以先打开弹幕窗口后 重新设置下置顶

**Comment by MistEO** [comment]
ok, thx~

**Comment by LoveLoliii** [comment]
fixed https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.5.3

**Comment by MistEO** [comment]
为什么版本号不往后叠加，而要用重复的呀。很容易乱啊

**Comment by LoveLoliii** [comment]
> 为什么版本号不往后叠加，而要用重复的呀。很容易乱啊

感觉没啥改动 怪怪的
