### ISSUE TITLE
小礼物很刷屏，能不能加个延迟一起弹出来

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#5]
比如这种感觉
```
XXX 赠送辣条 x 20
```

![image](https://user-images.githubusercontent.com/18511905/174431821-8aa3b787-c013-4585-9466-987aba1378c6.png)

**Comment by LoveLoliii** [comment]
好的

**Comment by LoveLoliii** [comment]
![9 IE{ PNH}5(Y1TS}SNUVHB](https://user-images.githubusercontent.com/12725100/174435810-60f847d4-3f89-4394-a4ad-6ff14d7b9be0.jpg)

**Comment by LoveLoliii** [comment]
added
