### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#6]
v1.8.5 不显示弹幕，之前用 v1.8.4 正常。另外这个布局也不太对好像，进入房间跑到中间了

![image](https://user-images.githubusercontent.com/18511905/205304125-7e9dfe58-2d33-418b-be50-b15b3891724a.png)
![image](https://user-images.githubusercontent.com/18511905/205304147-095f7d94-0f3c-4762-a618-30cdc40979ef.png)

**Comment by MistEO** [comment]
经测试 v1.8.4 也显示不了了，之前还可以用的，考虑这几天比较特殊，是不是啊 b 改了啥 api？

**Comment by LoveLoliii** [comment]
> 经测试 v1.8.4 也显示不了了，之前还可以用的，考虑这几天比较特殊，是不是啊 b 改了啥 api？

是的 ；布局的话我看看
