### ISSUE TITLE
希望能支持挂代理更新

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#7]
RT，裸连 github 网速实在不佳（

**Comment by LoveLoliii** [comment]
加入todolist

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月25日 22:40
收件人: ***@***.***>
抄送: ***@***.***>
主题: [kokolokksk/catcat-dm-react] 希望能支持挂代理更新 (Issue #7)


RT，裸连 github 网速实在不佳（

―

**Comment by LoveLoliii** [comment]
> RT，裸连 github 网速实在不佳（

https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.8.7
added
