### ISSUE TITLE
点击弹幕的菜单，希望新增复制用户昵称、复制弹幕内容、打开用户主页、打开用户直播间等菜单项

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#8]
![image](https://user-images.githubusercontent.com/18511905/209475779-089e7491-5ab5-482f-a521-a7117c048541.png)

还有啥能加的（

**Comment by LoveLoliii** [comment]
还能加个使用chatgpt回复他······

**Comment by LoveLoliii** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/209475779-089e7491-5ab5-482f-a521-a7117c048541.png)
> 
> 还有啥能加的（

https://github.com/kokolokksk/catcat-dm-react/releases/tag/v1.8.8
added

**Comment by MistEO** [comment]
> 还能加个使用chatgpt回复他······

草，那不得整一个

**Comment by LoveLoliii** [comment]
> > 还能加个使用chatgpt回复他······
> 
> 草，那不得整一个

整不出来*****************
