### ISSUE TITLE
v1.8.8 弹幕菜单显示不全

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/catcat-dm-react#9]
![image](https://user-images.githubusercontent.com/18511905/209661498-43c87edd-977d-4ede-b240-ee75f983fb04.png)

**Comment by LoveLoliii** [comment]
这个。

**Comment by LoveLoliii** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/209661498-43c87edd-977d-4ede-b240-ee75f983fb04.png)

隔壁前端🐏了没来，来了我问问他要怎么解决。

**Comment by LoveLoliii** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/209661498-43c87edd-977d-4ede-b240-ee75f983fb04.png)

解决了！用新版本把高度拉长点。
